### ISSUE TITLE
Change the wording in README about the Discord server

### ISSUE THREAD

**Issue by ykdojo** [csdojo-defaang/the-dojo-way#94]
We should now explain that it is also a dojo clan server, which is a perfect fit for this repo.

**Comment by tirthkp** [comment]
I can do it can you assign me this issue.

**Comment by tirthkp** [comment]
Hey there, thanks for assigning me this issue. I have to change the name only or I have to provide some description too? If any can you please elaborate some more details about it. Thanks

**Comment by ykdojo** [comment]
@tirthkp don't worry about it - I just made this change.
